# Generated by Django 4.2 on 2023-04-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='destinations',
            field=models.ManyToManyField(blank=True, related_name='booker', to='main.destination'),
        ),
    ]
