# Generated by Django 4.2 on 2023-04-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_destination_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='booked',
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='destinations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to='main.destination'),
        ),
        migrations.DeleteModel(
            name='BookedDestination',
        ),
    ]
